### ISSUE TITLE
If there are more examples, I try to multiplex on websocket, but none of them work

### ISSUE THREAD

**Issue by mmm8955405** [libp2p/js-libp2p-mplex#105]
const pipe = require('it-pipe')
const Mplex = require('libp2p-mplex')
const muxer = new Mplex()；

const wsStream = createWebsocket();
pipe(wsStream, muxer, wsStream)

I can't use nodejs's stream pipe API, 
{  
muxer.pipe(),  wsStream.pipe(muxer)
}
Using libp2p mplex, error is reported again：
Uncaught TypeError: fns.shift(...) is not a function

**Comment by mmm8955405** [comment]
I work on the most stable nodejs environment at present

**Comment by mmm8955405** [comment]
fns.shift(...) is not a function
    at rawPipe (C:\Users\lenovo\Desktop\electron\horse-client\node_modules\it-pipe\index.js:4)

If you use it-pipe to report an error,

Using nodejs steam pipe, reporting is not a method

**Comment by vasco-santos** [comment]
Hello @mmm8955405 

What is the `createWebsocket()` function? It seems that it is not an async iterable source . Have a look at https://gist.github.com/alanshaw/591dc7dd54e4f99338a347ef568d6ee9

**Comment by mmm8955405** [comment]
> Hello @mmm8955405
> 
> What is the `createWebsocket()` function? It seems that it is not an async iterable source . Have a look at https://gist.github.com/alanshaw/591dc7dd54e4f99338a347ef568d6ee9

Create a standard websocket stream :
As shown on the official website:

https://github.com/websockets/ws

```
const WebSocket = require('ws');
const ws = new WebSocket('wss://echo.websocket.org/', {
  origin: 'https://websocket.org'
});
const duplex = WebSocket.createWebSocketStream(ws, { encoding: 'utf8' });
duplex.pipe(process.stdout);
process.stdin.pipe(duplex);
```
This is indeed a standard asynchronous duplex stream, but the example you give cannot be reused on it at all

**Comment by mmm8955405** [comment]
I think it may be related to your dependence. Why do you rely on the third-party pipeline it pipe instead of node native

**Comment by mmm8955405** [comment]
I think it may be related to your dependence. Why do you rely on the third-party pipeline "it-pipe" instead of node native

**Comment by vasco-santos** [comment]
@mmm8955405 you cannot use `ws` directly, since it is not an async iterable.

There is an abstraction for `ws` on [alanshaw/it-ws](https://github.com/alanshaw/it-ws). Anyway, why don't you use [libp2p/js-libp2p-websockets](https://github.com/libp2p/js-libp2p-websockets) directly?

**Comment by mmm8955405** [comment]
js-libp2p-webSockets rely too much on libp2p, such as the need for upgrade. It's like a family bucket, using one project, you have to rely on another project. Sometimes it's too intrusive for architecture. And it has too few documents. I think only insiders will pay attention to it.



For a general Reuse Protocol, it should support the most basic things (such as NPM stream). Of course, asynchronous and iterative is a good idea, but it is not necessary. For example, mptt, XMPP, and other long connection protocols, can't their JS clients be reused if they don't support asynchronous and iterative? These should be your consideration.




At present, I can only choose to give up. I've looked at the libp2p project. From experience, libp2p should be reconstructed ~ it shouldn't do too many things.



Community level activity is a problem we need to consider.

I am a java engineer. In Java, many projects are making rounds repeatedly. But it doesn't make much sense.



Anyway, thank you very much for your answer

**Comment by vasco-santos** [comment]
@mmm8955405 you can provide an "empty" upgrader too for `libp2p-websockets` and you should be good to use it. 

I agree that the docs are oriented for `libp2p`. While the modularisation aims to make the modules usable with other stuff, the goal is to use them with libp2p in a configurable and modular approach.

I think that you did not understand that the issue that you are having is not related to `libp2p-mplex` itself. You are using `it-pipe` which is similar do node streams `pipe`, but for `async iterables`. However, you are providing it a stream that is not an async iterable (websockets), which is failing.

I recommended that you go with [alanshaw/it-ws](https://github.com/alanshaw/it-ws), as this is the simples approach here, as this is basically a wrapper that fully converts ws to an async iterable.

For more general use cases, such as mqtt, XMPP, you might probably be able to use [stream-to-it](https://github.com/alanshaw/stream-to-it) if they are node streams. Async iterators have a big advantage vs node streams and that is why we are using them.

**Comment by mmm8955405** [comment]
I know exactly what I'm doing and the problems I'm having.

But you don't seem to understand me.

1. I suggest that you support node stream, whether it's asynchronous or iterative. Because it's more generic.

2. You should decouple libp2p as much as possible, and write the reused protocol fields clearly in the project, rather than on the libp2p official website. This is good for other languages to implement the reuse protocol. This is very important when choosing to use a project. I think this is what you should do.

3. I don't want to use the it-ws, JS-libp2p-WebSockets, stream-to-it projects you suggest. Because their activity and attention are almost zero, and there is no performance test report or practice stability report. In front of the importance of this point, asynchrony and iteration are almost shit. However, you mentioned asynchronous and iterative several times, and suggested that I use projects that support asynchronous and iterative. You pay too much attention to one technology of language and ignore other more important problems, which is very bad in my opinion



4. I have a deep research in Java. I also have many attempts and concerns about C, PHP, go and ruby. The understanding of many things is not limited to the language itself. Of course, if you don't want your project to be extensible, you can ignore what I said
