### ISSUE TITLE
Stream.close should end the write not the read

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-mplex#110]
I was looking at some examples and realized that mplex streams are currently closing the read side of the stream on `Stream.close`. This behavior is not what I expect and also does not match the behavior of the go muxers, https://github.com/libp2p/go-libp2p-core/blob/v0.5.3/mux/mux.go#L22. 

`close` should end the stream for writing, not reading, and `reset` should close both (which it does).

cc @alanshaw @vasco-santos

**Comment by alanshaw** [comment]
Ha, oops. Should be pretty easy to fix though. Maybe because there's a `close` event on Node.js's Readable stream I got confused?

**Comment by jacobheun** [comment]
I think the confusion is around the mplex `Close<type>` messages. When mplex closes a stream it closes the read on the writer end and tells the receiver to close their read. Right now i think we're kind of overlapping user behavior with the muxers internal handling of the close messages.

**Comment by achingbrain** [comment]
Closing as this has been split out into `closeWrite` and `closeRead`, `close` calls them both but they can be called individually if required.
