### ISSUE TITLE
Message chunking

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-mplex#117]
Go already performs message size slicing in the stream. Currently, libp2p multiplexer fails if messages bigger than 1MB are provided, while the muxer should take care of the actual packet size that is sent over the network by chunking it.

References:
- https://github.com/ipfs/js-ipfs/issues/2799#issuecomment-730488760

**Comment by achingbrain** [comment]
We chunk outgoing messages [here](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/stream.ts#L172-L186) - please re-open if this isn't what you meant..
