### ISSUE TITLE
versions above 1.2.1 do not work in browser

### ISSUE THREAD

**Issue by abetaev** [libp2p/js-libp2p-mplex#191]
since v2.0.0 the following code
```typescript
(p2p: Libp2p) => {
  const connection = await p2p.dial(to)
  console.log('connected', connection)
  const { stream } = await connection.newStream(PROTOCOL);
  console.log('obtained stream', stream)
}
```
hangs on `connection.newStream` call in browser (firefox, chromium)

v1.2.1 works
v2.0.0, v3.0.0 and v4.0.0 don't work

**Comment by alanshaw** [comment]
+1 same for me

**Comment by achingbrain** [comment]
These need the next libp2p release - the tracking issue is here: https://github.com/libp2p/js-libp2p/pull/1253

**Comment by achingbrain** [comment]
This should work now, if you use the latest versions of all modules.  Please re-open if you continue to have problems.
