### ISSUE TITLE
restrictSize performance issue

### ISSUE THREAD

**Issue by tuyennhv** [libp2p/js-libp2p-mplex#205]
**Description**
- `restrictSize()` in libp2p-mplex@0.10.5 has taken 5% of cpu time in lodestar

<img width="1420" alt="Screen Shot 2022-08-19 at 11 30 04" src="https://user-images.githubusercontent.com/10568965/185543163-2e32facd-3113-4db6-90c2-d97d1b88b5a6.png">

- We have another branch with migrate to libp2p-mplex@5.0.0, and `restrictSize()` even took more than 11% of cpu time
<img width="1444" alt="Screen Shot 2022-08-19 at 11 31 34" src="https://user-images.githubusercontent.com/10568965/185543299-d022552c-82b6-45ac-80e4-3ec7ac348838.png">

**Comment by tuyennhv** [comment]
attaching 2 lodestar profiles above

- with libp2p-mplex 5.0.0
[0819_feat1_md16.cpuprofile.zip](https://github.com/libp2p/js-libp2p-mplex/files/9380493/0819_feat1_md16.cpuprofile.zip)

- with libp2p-mplex 0.10.5
[0819_unstable_md16.cpuprofile.zip](https://github.com/libp2p/js-libp2p-mplex/files/9380503/0819_unstable_md16.cpuprofile.zip)

**Comment by wemeetagain** [comment]
![Screenshot from 2022-08-19 08-38-23](https://user-images.githubusercontent.com/1348242/185631588-8ebc72f4-4ba4-4611-aecb-b3ac28883bf9.png)
I see this in the profile, I think the issue may be due to `node --inspect`

**Comment by tuyennhv** [comment]
@wemeetagain you're right, I wrote a benchmark and there's no different with or without the `restrictSize` function

**Comment by tuyennhv** [comment]
reopening the issue, I disabled "async stack trace" and it still shows 4% of cpu time is used for restrictSize

![](https://user-images.githubusercontent.com/10568965/193488316-0298a961-bb66-41da-b31c-0bca15d25bc8.png)

Detail

![](https://user-images.githubusercontent.com/10568965/193488341-dde5c4f5-ce46-40e3-a3d3-e4a4913c2642.png)

No async hook there @wemeetagain 

![](https://user-images.githubusercontent.com/10568965/193488238-bd028f47-9bd0-447e-86ae-eca4afb54d0c.png)

The version used in lodestar is @libp2p/mplex@5.2.4

**Comment by mpetrunic** [comment]
Triage notes: probably a side effect of not queuing up messages (which needs to be fixed).

**Comment by achingbrain** [comment]
> probably a side effect of not queuing up messages

Not sure about this - `restrictSize` is only used for incoming messages to ensure the remote hasn't sent us something bigger than the max supported message size, the queueing up of messages relates to outgoing messages instead.

**Comment by achingbrain** [comment]
> it still shows 4% of cpu time is used for restrictSize

What happens when you expand the tree all the way down?  From what I can see `restrictSize` takes 4%, but `runMicrotasks` takes 3.8%.  Most of the cpu time is in `yield * msg` which will wait before continuing so it might end up inside [this._handleIncoming](https://github.com/libp2p/js-libp2p-mplex/blob/master/src/mplex.ts#L211) since that's where control is yielded to, so it'd be good to dig a bit deeper.

**Comment by tuyennhv** [comment]
- Top down view:

<img width="1140" alt="Screen Shot 2022-11-23 at 10 23 56" src="https://user-images.githubusercontent.com/10568965/203463489-4c9af314-0e30-4467-a3f4-d8b2e025ced5.png">

- Bottom up view

<img width="1128" alt="Screen Shot 2022-11-23 at 10 24 37" src="https://user-images.githubusercontent.com/10568965/203463566-71a52080-1bd5-48c9-9aa7-08ef61ade32d.png">

**Comment by achingbrain** [comment]
I've refactored `restrictSize` out of the codebase here: https://github.com/libp2p/js-libp2p-mplex/pull/231 in order to apply the size limit before decoding messages instead of afterwards.

I don't think it's going to change the amount of CPU usage significantly as we're still doing the same operations so it might be worth re-running the benchmark after that PR is merged.

**Comment by achingbrain** [comment]
This has been shipped now - could you please re-run the benchmarks with `libp2p@next` and see if it's still a bottleneck?

**Comment by p-shahi** [comment]
@tuyennhv Please re-run the benchmarks when you get a chance 🙏

**Comment by achingbrain** [comment]
@tuyennhv will you have time to re-run these benchmarks soon?

**Comment by tuyennhv** [comment]
sorry I missed this, this was found during profiling a lodestar node. There's a work-in-progress to upgrade libp2p https://github.com/ChainSafe/lodestar/pull/4717 , will double check there
