### ISSUE TITLE
Use only pull-streams, reduce memory usage and improve perf by a **lot**

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p-mplex#73]
long story short: libp2p-mplex has been around for a while, longer than our migration for pull-streams. Things work now but we know that using Readable Streams in the browser is a huge memory inefficiency and might cause bugs that we are not even aware right now.

Now that #68 #72 happened. We should upgrade the whole module to drop Readable Streams entirely.

**Comment by diasdavid** [comment]
This should be considerably simpler now that there is https://github.com/libp2p/mplex

This would remove the Readable Stream shims from libp2p as a whole!

**Comment by diasdavid** [comment]
@dryajov can you share an update here on the perf boost and mem improvements?

**Comment by dryajov** [comment]
Per related info is here - https://github.com/libp2p/pull-mplex/pull/4.

**Comment by vasco-santos** [comment]
Not relevant anymore after the async refactor of this module
