### ISSUE TITLE
Avoid multiple conversions between node streams and pull streams

### ISSUE THREAD

**Issue by mcollina** [libp2p/js-libp2p-mplex#89]
This module converts between streams and pull streams several times, increasing memory usage, latency and cpu usage on the hot path of receiving data.

The `mplex.listener(stream)` method require a pull stream. However, that pull stream is automatically converted into a node core stream in https://github.com/libp2p/js-libp2p-mplex/blob/aa977c077266bef8383ca2aeaefcdcc12b11fe3e/src/index.js#L11.
This is going to lead to adding _two_ layers to abstractions that are not needed on Node.js, as `mplex` core multiplexer is implemented as a Node.js duplex (https://github.com/libp2p/js-libp2p-mplex/blob/aa977c077266bef8383ca2aeaefcdcc12b11fe3e/src/internals/index.js#L28).

My recommendation is to move the internal multiplexer to a pull-stream only implementation, because that will also remove the conversion needed when emitting a new stream (https://github.com/libp2p/js-libp2p-mplex/blob/aa977c077266bef8383ca2aeaefcdcc12b11fe3e/src/muxer.js#L47). In turn, this create even more overhead.

Overall, this module introduces 5/6 levels of data buffering, where 1 or 2 could suffice (each layer introduce latency. As a general rule, every time you pipe two streams it adds some data buffering and latency.

---

When doing this port to pull-stream, I recommend to remove one of the main buffering layer. Currently the module creates a Duplex stream which is piped back and fort (https://github.com/libp2p/js-libp2p-mplex/blob/aa977c077266bef8383ca2aeaefcdcc12b11fe3e/src/index.js#L21). Note that this duplex is only internal, and it is not exposed, so it's totally unnecessary. It's possible to use the native node core or pull stream methods to read and write to it, saving a buffering layer.

---

Another element of latency is introduced by the usage of duplexify, which adds one unneeded level of buffering. Duplexify is used to assemble shared streams in https://github.com/libp2p/js-libp2p-mplex/blob/aa977c077266bef8383ca2aeaefcdcc12b11fe3e/src/internals/index.js#L138. Even if it's convenient, creating dupexes in this way is inefficient, and they should but created as duplex from the start.

**Comment by vasco-santos** [comment]
It's done 🎉
