### ISSUE TITLE
Document meanings of state (0, 1, 2, ...)

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-mplex#92]
Trying to debug a thing and minimally reading through mplex, hard to understand the meaning of the state values. State is 2, what does this mean. Consider using constants to refer to the state.
```js
const OPEN = 0
const UNINITIALIZED = 2
const CLOSED = 3
```
( numbers + names above are examples )

**Comment by vasco-santos** [comment]
This should not be relevant anymore after the latest release. Feel free to re-open this if needed
